# Generated by Django 5.2.5 on 2025-08-27 00:30

from time import timezone
from django.db import migrations

def create_initial_data(apps, schema_editor):
    Category = apps.get_model('AppTienda', 'Category')
    # Create initial categories
    Category.objects.create(name='Electronics')
    Category.objects.create(name='Clothing')
    Category.objects.create(name='Home & Kitchen')

    Store = apps.get_model('AppTienda', 'Store')
    # Create initial stores
    Store.objects.create(name='Best Electronics', description='Your one-stop shop for all electronics.', address='123 Tech Street', google_maps_link='https://goo.gl/maps/example1', email='contact@bestelectronics.com', created_at=timezone.now(), image_url='https://example.com/image1.jpg', category=Category.objects.get(name='Electronics'))
    Store.objects.create(name='Fashion Hub', description='Trendy clothing and accessories.', address='456 Fashion Ave', google_maps_link='https://goo.gl/maps/example2', email='info@fashionhub.com', created_at=timezone.now(), image_url='https://example.com/image2.jpg', category=Category.objects.get(name='Clothing'))
    Store.objects.create(name='Home Essentials', description='Everything you need for your home.', address='789 Home St', google_maps_link='https://goo.gl/maps/example3', email='support@homeessentials.com', created_at=timezone.now(), image_url='https://example.com/image3.jpg', category=Category.objects.get(name='Home & Kitchen'))

    # Create initial products
    Product = apps.get_model('AppTienda', 'Product')
    Product.objects.create(name='Smartphone', description='Latest model smartphone with advanced features.', price=699.99, stock=50, created_at=timezone.now(), store=Store.objects.get(name='Best Electronics'))
    Product.objects.create(name='Jeans', description='Stylish denim jeans for everyday wear.', price=49.99, stock=100, created_at=timezone.now(), store=Store.objects.get(name='Fashion Hub'))
    Product.objects.create(name='Blender', description='High-speed blender for smoothies and more.', price=89.99, stock=30, created_at=timezone.now(), store=Store.objects.get(name='Home Essentials'))

    User = apps.get_model('AppTienda', 'User')
    User.objects.create(password='hashed_password', last_login=timezone.now(), is_superuser=True, username='admin', first_name='Admin', last_name='User', is_staff=True, is_active=True, date_joined=timezone.now(), email='admin@example.com', role='vendor', created_at=timezone.now(), image_url='https://example.com/image4.jpg', groups=[], user_permissions=[])

class Migration(migrations.Migration):

    dependencies = [
        ('AppTienda', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_data),
    ]
